---
  - hosts: control
    become: true
    #become_user: root
    tasks:
# Adding a name to a task and running the command
#      - name: Install web packages # ( the update_cache=yes does apt-get update -y )


       - name: Install update packages # ( the update_cache=yes does apt-get update -y )
         apt: name=update state=present update_cache=yes
       - name: Install web curl # ( the update_cache=yes does apt-get update -y )
      #apt: name=apache2 state=present update_cache=yes
         apt: name={{item}} state=present update_cache=yes
         with_items:
           - curl
           - software-properties-common
           - repository ppa:ansible/ansible
           - update
           - ansible
           - update
           - python-httplib2
#           ansible@control:~/ansible-dev/playbooks$ curl app01/db
#           Database Connected from app01!
#           ansible@control:~/ansible-dev/playbooks$ curl app02/db
#           Database Connected from app02!
#           ansible@control:~/ansible-dev/playbooks$ curl lb01/db
#           Database Connected from app02!
## check database system to ensure database has beeen created and user account
# mysql -u root -p
# show databases;
# SELECT User FROM mysql.user;
