---
  - hosts: database
    tasks:
    become: true
    become_user: root
# Adding a name to a task and running the command
      - name: Install packages mysql-server #( the update_cache=yes does apt-get update -y )
        apt: name=mysql-server state=present update_cache=yes

      - name: Install update packages # ( the update_cache=yes does apt-get update -y )
        apt: name=update state=present update_cache=yes

      - name: Check if mysql-server has started
        service: name=mysql state=started enabled=yes
