---
  - hosts: database
    tasks:
    become: true
    become_user: root
# Adding a name to a task and running the command
      - name: Install packages mysql-server #( the update_cache=yes does apt-get update -y )
        apt: name=mysql-server state=present update_cache=yes

      - name: Install update packages # ( the update_cache=yes does apt-get update -y )
        apt: name=update state=present update_cache=yes

      - name: install tools
        apt: name={{item}} state=present update_cache=yes
        with_items:
        - python-mysqldb

      - name: Check if mysql-server has started
        service: name=mysql state=started enabled=yes

      - name: ensure mysql listening on all ports
        lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
        notify: restart mysql

      - name: create demo database
        mysql_db: name=demo state=present

      - name: create demo user
        mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

        # check database system to ensure database has beeen created and user account
        # mysql -u root -p
        # show databases;
        # SELECT User FROM mysql.user;

     handlers:
      - name: restart mysql
        service: name=mysql state=restarted
